### ISSUE TITLE
Provide automatic migration 23.1 -> 23.4

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/secret-operator#251]
The CHANGELOG states the following for 23.4:
```
- Shortened the registration socket path for Microk8s compatibility ([#231]).
  - After upgrading you will need to
    `rmdir /var/lib/kubelet/plugins_registry/secrets.stackable.tech-reg.sock` manually.
    This applies to *all* users, not just Microk8s.
```
It would be great if we could somehow migrate that automatically, e.g. have some sort of "delete /var/lib/kubelet/plugins_registry/secrets.stackable.tech-reg.sock if it is a directory" command during secret-operator startup.
This is especially important for managed k8s where you don't have (easy) access to k8s node shells.

**Comment by lfrancke** [comment]
I'll add this to the board now but will reevaluate after refinement whether we want to do it or not.
