### ISSUE TITLE
Document why root is required

### ISSUE THREAD

**Issue by nightkr** [stackabletech/secret-operator#255]
Basically: clean up and add to the docs:

1. We need to create two unix domain socket listeners in hostPath volumes where Kubelet can find them, so we need FS write permissions (one of them can theoretically be anywhere, one of them needs to be in a particular folder specified by the kubelet)
2. CSI tells us "put your files that you want to inject into the pod in this FS path please", we need FS permissions to create and write to that folder

[[source from Slack]](https://stackable-workspace.slack.com/archives/C03P3MUPJDT/p1679479001215299)

## Acceptance Criteria
- [ ] the need for root is explained somewhere in the secret operator docs (where exactly is up to the person picking up the ticket, and at the descretion of a reviewing person)

**Comment by fhennig** [comment]
I guess it could just be an extra page, or if it's just a short text blurp it could also go into the index.adoc I guess.
