### ISSUE TITLE
"failed to create secret parent dir" issue appears when deploy in kubernetes cluster in ibm cloud

### ISSUE THREAD

**Issue by positively** [stackabletech/secret-operator#298]
### Affected version

23.4.0

### Current and expected behavior

**Description:**
Following this documentation - https://docs.stackable.tech/home/stable/hive/getting_started/first_steps.html
you will get stuck on the last step when you need to deploy resource `kind: HiveCluster`. You will receive events with rpc error (read bellow for details)

**Environment:**
Kubernetes cluster version `1.25.11_1549` in IBM cloud. 

**Issue:**
```
MountVolume.SetUp failed for volume "pvc-4d63226d-5b48-45f9-9001-2254c33625e2" :
rpc error: code = Unavailable desc = failed to create secret parent dir
/var/data/kubelet/pods/1d5c9abf-2183-4414-b031-33514ce231e9/volumes/kubernetes.io~csi/pvc-4d63226d-5b48-45f9-9001-2254c33625e2/mount:
No such file or directory (os error 2)
```

**Cause:**
Node has path for kubelet `/var/data/kubelet` and it has also symlink `/var/lib/kubelet` to that path.
```
root@kube-cio0njmf0eqbnpa4mpdg-hiveeude1bx-default-0000011f:/# ls -la /var/lib/kubelet
lrwxrwxrwx 1 root root 17 Jul 13 14:53 /var/lib/kubelet -> /var/data/kubelet
```
but these code defines path with symlink and not origin.
```
    #[snafu(display("failed to create secret parent dir {}", path.display()))]
    CreateDir {
        source: std::io::Error,
        path: PathBuf,
    },
```
src: https://github.com/stackabletech/secret-operator/blob/main/rust/operator-binary/src/csi_server/node.rs#L52

**Workaround:**
create the symlink in pod `secret-operator-daemonset-xxxxx` in container `secret-operator`
```
mkdir /var/data
ln -s /var/lib/kubelet /var/data/kubelet
```
After that resource HiveCluster can start operate properly without error messages.

But this is only workaround, it will be cool if someone shed the light on this issue and make a good fix for it!

### Environment

```
$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.25.11+IKS
WARNING: version difference between client (1.27) and server (1.25) exceeds the supported minor version skew of +/-1
```

### Would you like to work on fixing this bug?

no

**Comment by sbernauer** [comment]
Hi @positively thanks for your detailed report!
We already had issues in the past with huawei cloud not having the "default" kubelet path and have documented the proper solution in https://docs.stackable.tech/home/nightly/secret-operator/installation.html#_huawei_cloud.

Could you please test adding the argument `--set kubeletDir=/var/data/` to the helm install command?
In case that works I would document the changes needed for IBM cloud.
Maybe there is some clever way we can automatically detect the environment and handle this automatically going forward. Not sure if helm allows this though...

**Comment by positively** [comment]
It works with parameter `--set kubeletDir=/var/data/kubelet`

entire command:
```
helm install --wait secret-operator stackable-stable/secret-operator --version 23.4.0 --set kubeletDir=/var/data/kubelet
```

logs from container "secret-operator":
```
2023-07-20T07:20:06.626188Z  INFO stackable_secret_operator::csi_server::node: Received NodePublishVolume request volume.path=/var/data/kubelet/pods/e29eba00-415f-47c4-9c2d-3d4d8515b986/volumes/kubernetes.io~csi/pvc-7f46e833-17ba-4152-9233-82a6421abca6/mount
2023-07-20T07:20:47.139175Z  INFO stackable_secret_operator::csi_server::node: Received NodeUnpublishVolume request volume.path=/var/data/kubelet/pods/3d6ba70e-536c-4477-86fe-1fcdf067a9f9/volumes/kubernetes.io~csi/pvc-19a2b19b-f28b-4143-8865-e2c7e0e8bf1a/mount
```

it turns out that this is not a bug... sorry for the confusion and thanks for your help!
