### ISSUE TITLE
Kerberos keytab provisioning

### ISSUE THREAD

**Issue by nightkr** [stackabletech/secret-operator#4]
The operator should (optionally) be able to provision Kerberos keytabs dynamically from the KDC, rather than reading them from static secrets.

Acceptance criteria:

- Backend/type configuration - #8 
- Load admin keytab and KDC mapping
- Create pod keytab for a given scope (node FQDN, pod FQDN, etc) on demand

**Comment by fhennig** [comment]
There seems to be at least *some* crate to work with kerberos in rust (haven't looked into it much): https://docs.rs/kerbeiros/latest/kerbeiros/
