### ISSUE TITLE
Allow specifying a fixed prefix and maximum allowed length for accounts generated by the Active Directory backend

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/secret-operator#449]
We should enhance the secret operator to give a certain degree of influence over the accounts that it generates in active directory, when using this backend for Kerberos principals.

Necessary functionality:
- specify a fixed prefix that should be prepended to all `samaccountname`s of like for example "svc01"
- specify a maximum length for the overall length of samaccountname (if used in conjunction with the prefix, the overall length counted together with the prefix and the generated portion of the name should not exceed this value)

**Comment by nightkr** [comment]
I was confusing CN and samAccountName here. CN is problematic, sAN is just random anyway so we can set it to whatever.

**Comment by lfrancke** [comment]
Can you please include a link to the docs and include a snippet we can use for the release notes?

**Comment by maxgruber19** [comment]
Just wanted to let you know that this is perfectly fine, we're looking forward to 24.11 :-) thanks for your quick solution
