### ISSUE TITLE
Add Cert-Manager backend

### ISSUE THREAD

**Issue by nightkr** [stackabletech/secret-operator#474]
Builds on #473 by automatically creating the applicable Cert-Manager Certificate objects, and mounting in the applicable certificates.

**Comment by lfrancke** [comment]
Can you please add a link to the documentation as well as a short snippet for the release notes?

And would it be useful to show this off to the team?

**Comment by nightkr** [comment]
Docs: https://docs.stackable.tech/home/nightly/secret-operator/cert-manager

Relnote: "The Stackable Data Platform now supports provisioning TLS certificates using cert-manager."

> And would it be useful to show this off to the team?

Maybe? Probably worth mentioning that it exists, but as an operator dev it _should_ be transparent.

**Comment by nightkr** [comment]
Demo:
https://github.com/user-attachments/assets/91329cc6-5076-4b2c-8b94-db63a87a621d
