### ISSUE TITLE
Modify key length for cert-manager certificates

### ISSUE THREAD

**Issue by nightkr** [stackabletech/secret-operator#527]
#465 covered `autoTls`, but we should apply the same logic to `experimentalCertManager` as well.

**Comment by nightkr** [comment]
Release note: "The Stackable Secret Operator's `experimentalCertManager` backend now supports specifying custom key lengths (like the `autoTls` backend has supported since 24.11)."

**Comment by lfrancke** [comment]
Is this going to be in 25.3 or 24.11.1?
