### ISSUE TITLE
CAs should not be created automagically

### ISSUE THREAD

**Issue by lfrancke** [stackabletech/secret-operator#67]
As a user I'd like it to be my concious choice whether a CA should be created automatically or not when the referenced Secret does not exist so that I am informed about any typos I might have in my definitions (or even just the order of applies being wrong).

**Comment by teozkr** [comment]
I kind of disagree here. To me, integrating into an existing PKI is a corner case that needs to be supported, but that I'm not super willing to sacrifice too many ergonomics for.

Maybe a compromise would be to have the CRD default to `generate: false`, but to ship a `tls` `AuthenticationClass` with the chart that has `generate: true` (but which can be disabled wholesale and replaced by the user if they want to use an alternative method).

**Comment by lfrancke** [comment]
Understood. I definitely want this configurable and I also believe the default should be `false` as you suggest.

@soenkeliebau : Opinions?
